{"name":"nonExistUser","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected:<Пользователь с логином block_user заблокирован> but was:<Пользователь с логином fail_user не найден>","trace":"java.lang.AssertionError: expected:<Пользователь с логином block_user заблокирован> but was:<Пользователь с логином fail_user не найден>\r\n\tat org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)\r\n\tat org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)\r\n\tat ru.rt.crc.pages.LoginPage.checkMessage(LoginPage.java:32)\r\n\tat tests.LoginTests.nonExistUser(LoginTests.java:37)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.ArrayList.forEach(ArrayList.java:1257)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:766)\r\n\tat org.testng.TestRunner.run(TestRunner.java:587)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1109)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1039)\r\n\tat org.testng.TestNG.run(TestNG.java:1007)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"fail_password","value":"fail_password"},{"name":"innerUser","value":"nikitina-ar"},{"name":"block_user","value":"block_user"},{"name":"password","value":"qwerty"},{"name":"fail_user","value":"fail_user"}],"start":1632297180074,"stop":1632297180722,"uuid":"7e39a5c5-3da9-4092-a785-a0d1039494bb","historyId":"f3ed566744734adfb0c94b9054fdab0c","fullName":"tests.LoginTests.nonExistUser","labels":[{"name":"package","value":"tests.LoginTests"},{"name":"testClass","value":"tests.LoginTests"},{"name":"testMethod","value":"nonExistUser"},{"name":"parentSuite","value":"LoginSuite"},{"name":"suite","value":"LoginTests"},{"name":"subSuite","value":"tests.LoginTests"},{"name":"host","value":"DESKTOP-MIC0JEQ"},{"name":"thread","value":"15128@DESKTOP-MIC0JEQ.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"feature","value":"Авторизация"}],"links":[]}